packages:
  - apps/*
  - packages/*
  - plugins/definitions/*
  - plugins/implementations/*
  - plugins/features/*
  - plugins/adapters/*
allowBuilds:
  '@google/genai': false
  better-sqlite3: true
  esbuild: true
  protobufjs: false
  vue-demi: true
