export function markup(registration) {
  return `<div class="intro"><p class="eyebrow">ACCOUNT CENTER</p><h1>从你的账号开始。</h1><p>登录 Antarestra，管理你的身份与访问权限。</p></div>
<p id="message" role="status" aria-live="polite" hidden></p>
<section id="guest" class="card"><nav aria-label="认证方式"><button id="show-login" class="selected">登录</button>${registration ? '<button id="show-register">创建账号</button>' : ''}</nav>
<form id="login"><h2>欢迎回来</h2><label>邮箱<input name="email" type="email" autocomplete="username" required maxlength="254"></label><label>密码<input name="password" type="password" autocomplete="current-password" required minlength="8" maxlength="128"></label><button class="primary">登录</button></form>
${registration ? '<form id="register" hidden><h2>创建你的账号</h2><label>显示名称<input name="displayName" autocomplete="nickname" required maxlength="128"></label><label>邮箱<input name="email" type="email" autocomplete="username" required maxlength="254"></label><label>密码<input name="password" type="password" autocomplete="new-password" required minlength="8" maxlength="128"></label><p class="hint">使用 12 到 128 个字符。邮箱作为登录名使用。</p><button class="primary">创建账号</button></form>' : ''}</section>
<section id="account" class="card" hidden><div class="row"><h2 id="welcome">当前账号</h2><button id="logout">退出登录</button></div><p id="principal"></p><p class="hint">访问权限由管理员分配，注册账号不会自动取得管理权限。</p></section>
<section id="users-panel" class="card wide" hidden><div class="row"><h2>本地用户</h2><button id="refresh-users">刷新</button></div><div id="users"></div><div class="row"><button id="previous">上一页</button><span id="page-number"></span><button id="next">下一页</button></div></section>
<section id="roles-panel" class="card wide" hidden><h2>角色与权限</h2><p id="permissions" class="hint"></p><div id="roles"></div><form id="role-form"><h3>创建或更新角色</h3><div class="grid"><label>角色标识<input name="id" required maxlength="128" placeholder="例如 operator"></label><label>角色名称<input name="name" required maxlength="128" placeholder="例如 运营人员"></label></div><label>权限标识（英文逗号分隔）<input name="permissions" placeholder="identity.local.manage"></label><button class="primary">保存角色</button></form></section>
<section id="bindings-panel" class="card wide" hidden><h2>分配角色</h2><form id="binding-form"><label>主体标识<input name="principalId" required maxlength="128" placeholder="从用户卡片选择或粘贴主体标识"></label><div class="grid"><label>角色标识<input name="roleId" required maxlength="128"></label><label>授权范围<input name="scope" value="system" required maxlength="128"></label></div><p class="hint">system 用于系统管理；空间权限必须绑定到准确的空间标识。</p><div class="row"><button class="primary" name="action" value="grant">授予角色</button><button name="action" value="revoke">撤销手动绑定</button><button id="load-bindings" type="button">查看绑定</button></div></form><pre id="bindings"></pre></section>
`
}
